channels:
- huggingface
- pytorch
- anaconda
- conda-forge
- defaults
dependencies:
- python=3.8.13
- black=22.6.0
- jupyter=1.0.0
- matplotlib=3.2.2
- seaborn=0.11.2
- tianshou=0.4.9
- transformers=4.21.1
- pytorch-lightning==1.7.2
- pip
- pip:
  - alembic==1.8.1
  - autopage==0.5.1
  - cliff==4.0.0
  - cmaes==0.8.2
  - cmd2==2.4.2
  - colorlog==6.6.0
  - distlib==0.3.6
  - greenlet==1.1.3
  - importlib-resources==5.9.0
  - jsonschema==4.14.0
  - mako==1.2.1
  - optuna==2.10.1
  - pbr==5.10.0
  - pkgutil-resolve-name==1.3.10
  - prettytable==3.4.0
  - pyperclip==1.8.2
  - pyrsistent==0.18.1
  - sqlalchemy==1.4.40
  - stevedore==4.0.0
  - mega.py==1.0.8 